-- Find the number of Apple product users and the number of total users with a device and group the counts by language. 
-- Assume Apple products are only MacBook-Pro, iPhone 5s, and iPad-air. 
-- Output the language along with the total number of Apple users and users with any device. 
-- Order your results based on the number of total users in descending order.
-- Tables: playbook_events, playbook_users.

-- Expected Output
-- language	n_apple_user	n_total_users
-- english	    11	                45
-- spanish	    3	                9
-- japanese	2	                6
-- french	    0	                5
-- russian	    0	                5
