-- Find the date with the highest total energy consumption from the Meta/Facebook data centers. 
-- Output the date along with the total energy consumption across all data centers.
-- Tables: fb_eu_energy, fb_asia_energy, fb_na_energy